"""Add created_at to video table

Revision ID: abc23565258e
Revises: d8d5a00f301c
Create Date: 2025-12-04 23:30:46.442004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abc23565258e'
down_revision = 'd8d5a00f301c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('forum_post_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('forum_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('forum_reply_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('forum_reply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('forum_reply_ibfk_2'), 'user', ['author_id'], ['id'])
        batch_op.drop_column('student_id')

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('forum_post_ibfk_2'), 'user', ['author_id'], ['id'])
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
