"""Rename uploaded_at to created_at in Material

Revision ID: d8d5a00f301c
Revises: 
Create Date: 2025-12-03 09:41:40.393250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8d5a00f301c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
